resolver: lts-19.28
packages:
- .
ghc-options:
  "$locals":
    -Wall -Wcompat -Werror -Widentities
    -Wincomplete-record-updates -Wincomplete-uni-patterns
    -Wmissing-home-modules -Wmissing-export-lists -Wpartial-fields
    -Wredundant-constraints -Wunused-packages -Wmissing-deriving-strategies
extra-deps:
- env-guard-0.2@sha256:59410eed9b9ddbd115760a59c7170927320d8612e414701d323a0c8985c97523,1251
- tasty-hedgehog-1.2.0.0@sha256:3deb98e9a9de9e27c25d02b7fe92ad5cf68d5163fdaaf35bca3923b3e671d46d,1803
- git: https://github.com/tbidne/algebra-simple.git
  commit: 2c8a79e8d3bf67c99e4851c557bf68a44c512307
- git: https://github.com/tbidne/bounds.git
  commit: 004f03aec46f29069fd0bf5115a384cd2b3141b3
nix:
  shell-file: nix/stack.nix
